json.id weapon.id
json.itype weapon.itype
json.name weapon.name
json.power_type weapon.power_type
json.power weapon.power
json.p_bonus weapon.p_bonus
json.attr_bonus weapon.attr_bonus
json.luck weapon.luck
json.cheese_effect weapon.cheese_effect