json.id @item.id
json.name @item.name
json.category @item.category.name
json.power_type @item.power_type
json.power @item.power
json.p_bonus @item.p_bonus
json.attr_bonus @item.attr_bonus
json.luck @item.luck
json.cheese_effect @item.cheese_effect