mh_groups = [
 "Indigenous Mice",
 "Dock Dwellers",
 "Mountain Mice",
 "Forest Guild",
 "Lab Experiments",
 "The Shadow Clan",
 "Digby Dirt Dwellers",
 "Followers of Furoma",
 "The Forgotten Mice",
 "Aquatic Order",
 "The Elub Tribe",
 "The Nerg Tribe",
 "The Derr Tribe",
 "The Dreaded Horde",
 "Draconic Brood",
 "Balack's Banished",
 "Gauntlet Gladiators",
 "Seasonal Soldiers",
 "Wizard's Pieces",
 "Zurreal's Breed",
 "Icewing's Invasion",
 "Wild Bunch",
 "Train Robbers",
 "Meteorite Miners",
 "The Marching Flame",
 "Muridae Market Mice",
 "Living Garden Mice",
 "Lost City Mice",
 "Sand Dunes Mice",
 "Queso Canyoneers",
 "Deep Sea Dwellers",
 "Fungal Fiends",
 "Citizens of Zokor",
 "Moussu Picchu Inhabitants",
 "Floating Islanders",
 "Rift Walkers",
 "Rift Stalkers",
 "The Polluted",
 "Event Mice",
]

mh_groups.each do |group|
  Group.find_or_create_by!(name: group)
end