mh_groups = [
  {:mh_code=>"common", :name=>"Indigenous Mice"}, 
  {:mh_code=>"dock", :name=>"Dock Dwellers"},
  {:mh_code=>"mountain", :name=>"Mountain Mice"}, 
  {:mh_code=>"forest", :name=>"Forest Guild"}, 
  {:mh_code=>"lab", :name=>"Lab Experiments"}, 
  {:mh_code=>"shadow", :name=>"Shadow Clan"}, 
  {:mh_code=>"dirt", :name=>"Digby Dirt Dwellers"}, 
  {:mh_code=>"furoma", :name=>"Followers of Furoma"}, 
  {:mh_code=>"forgotten", :name=>"The Forgotten Mice"}, 
  {:mh_code=>"hydro", :name=>"Aquatic Order"}, 
  {:mh_code=>"elub", :name=>"The Elub Tribe"}, 
  {:mh_code=>"nerg", :name=>"The Nerg Tribe"}, 
  {:mh_code=>"derr", :name=>"The Derr Tribe"}, 
  {:mh_code=>"dread", :name=>"The Dreaded Horde"}, 
  {:mh_code=>"dracaonic", :name=>"Draconic Brood"}, 
  {:mh_code=>"balack", :name=>"Balack's Banished"}, 
  {:mh_code=>"gauntlet", :name=>"Gauntlet Gladiators"}, 
  {:mh_code=>"seasonal", :name=>"Seasonal Soldiers"}, 
  {:mh_code=>"chess", :name=>"Wizard's Pieces"}, 
  {:mh_code=>"zzlibrary", :name=>"Zurreal's Breed"}, 
  {:mh_code=>"iceberg", :name=>"Icewing's Invasion"}, 
  {:mh_code=>"wild_bunch", :name=>"Wild Bunch"}, 
  {:mh_code=>"train_robbers", :name=>"Train Robbers"}, 
  {:mh_code=>"fort_rox", :name=>"Meteorite Miners"}, 
  {:mh_code=>"desertarmy", :name=>"The Marching Flame"}, 
  {:mh_code=>"desertmarket", :name=>"Muridae Market Mice"}, 
  {:mh_code=>"living_garden", :name=>"Living Garden Mice"}, 
  {:mh_code=>"lost_city", :name=>"Lost City Mice"}, 
  {:mh_code=>"sand_dunes", :name=>"Sand Dunes Mice"}, 
  {:mh_code=>"queso_canyon", :name=>"Queso Canyoneers"}, 
  {:mh_code=>"deep_sea_dwellers", :name=>"Deep Sea Dwellers"}, 
  {:mh_code=>"fungal_cavern", :name=>"Fungal Fiends"}, 
  {:mh_code=>"ancient_city", :name=>"Citizens of Zokor"}, 
  {:mh_code=>"moussu_picchu", :name=>"Moussu Picchu Inhabitants"}, 
  {:mh_code=>"floating_island", :name=>"Floating Islanders"}, 
  {:mh_code=>"rift_walkers", :name=>"Rift Walkers"}, 
  {:mh_code=>"rift_stalkers", :name=>"Rift Stalkers"}, 
  {:mh_code=>"polluted", :name=>"The Polluted"}, 
  {:mh_code=>"event", :name=>"Event Mice"},
]

mh_groups.each do |group|
  Group.find_or_create_by!(group)
end